[package]
name = "borealis-coordinator"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.8.9"
borealis-protocol.workspace = true
chrono.workspace = true
dotenv = "0.15.0"
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.9.0", features = ["runtime-tokio", "postgres", "chrono"] }
tokio = { version = "1.53.1", features = ["full"] }
